name: Create requirements

on:
  push:
    branches:
      - main  

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  

    - name: Install poetry
      run: pip install poetry

    - name: Create requirements.txt
      run: poetry export -f requirements.txt -o requirements.txt

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      permissions:
      contents: write
      with:
        commit_message: Create requirements.txt
